language: python
python:
    - "2.7"

env:
    - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
    - PLATFORMIO_PROJECT_DIR=examples/arduino-internal-libs

install:
    # tmp solution, use 32-bits toolchain
    - sudo apt-get install -qq lib32z1 lib32ncurses5 lib32bz2-1.0

    - pip install -U https://github.com/platformio/platformio/archive/feature/platformio-30.zip
    - platformio platform install file://.

script:
    - platformio run -d $PLATFORMIO_PROJECT_DIR
